services:
  wx-push:
    image: wx-push
    container_name: wx-push
    build: .
    restart: always
    ports:
      - "11180:11180"
    environment:
      - CORP_ID=${CORP_ID}
      - CORP_SECRET=${CORP_SECRET}
      - AGENT_ID=${AGENT_ID}
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true